version: '3.2'

services:
  influxdb:
    build: ./docker/DockerGrafanaInfluxKit/influxdb
    env_file: ./docker/DockerGrafanaInfluxKit/configuration.env
    hostname: influxdb
    networks:
      - network
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    networks:
      - network
    build: ./docker/DockerGrafanaInfluxKit/grafana
    env_file: ./docker/DockerGrafanaInfluxKit/configuration.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

  retail-analytics:
    image: retail-analytics:latest
    ports:
      - "5000:5000"
    container_name: retail-analytics
    networks:
      - network
    depends_on:
      - influxdb
      - grafana
    command: ["bash", "-c", "source /opt/intel/openvino/bin/setupvars.sh && cd application && python3 smart_retail_analytics.py -fm /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/FP32/face-detection-adas-0001.xml -pm /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/Transportation/object_attributes/headpose/vanilla_cnn/dldt/FP32/head-pose-estimation-adas-0001.xml -mm /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/Retail/object_attributes/emotions_recognition/0003/dldt/FP32/emotions-recognition-retail-0003.xml -om ../resources/FP32/mobilenet-ssd.xml -pr /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/Retail/object_detection/pedestrian/hypernet-rfcn/0026/dldt/FP32/person-detection-retail-0002.xml -lb ../resources/labels.txt -l /opt/intel/openvino/inference_engine/lib/intel64/libcpu_extension_sse4.so -ip influxdb"]

volumes:
  grafana_data: {}
  influxdb_data: {}

networks:
  network:
    driver: "bridge"

